apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    component: web-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-svc
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    component: web-adminer
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8089
  selector:
    component: web-backend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    component: web-frontend
